replicaCount: 1

image:
  repository: dockersamples/examplevotingapp_vote
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "vote.local"

redis:
  host: "redis-master.redis.svc.cluster.local"
  port: "6379"

vote:
  option1: "Cats"
  option2: "Dogs"
  title: "Azure Voting App"